# Generated by Django 3.2.4 on 2021-07-27 13:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    replaces = [('app', '0001_initial'), ('app', '0002_auto_20210621_1520'), ('app', '0003_auto_20210621_1632'), ('app', '0004_withdrawrequest'), ('app', '0005_withdrawrequest_datetime'), ('app', '0006_withdrawrequest_txid'), ('app', '0007_artwork'), ('app', '0008_auto_20210702_1556'), ('app', '0009_artwork_moderation_passed'), ('app', '0010_artwork_uuid'), ('app', '0011_artwork_minted')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=64)),
                ('username', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('name', models.TextField()),
                ('bio', models.TextField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='')),
                ('twitch', models.CharField(blank=True, max_length=64, null=True)),
                ('instagram', models.CharField(blank=True, max_length=64, null=True)),
                ('twitter', models.CharField(blank=True, max_length=64, null=True)),
                ('onlyfans', models.CharField(blank=True, max_length=64, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('_wallet_pk', models.BinaryField(blank=True, null=True)),
                ('balance_bnb', models.DecimalField(decimal_places=18, default=0, max_digits=64)),
                ('balance_lof', models.DecimalField(decimal_places=18, default=0, max_digits=64)),
                ('_wallet_address', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=18, default=0, max_digits=64)),
                ('currency', models.CharField(choices=[('bnb', 'Bnb'), ('lof', 'Lof')], max_length=3)),
                ('address', models.CharField(max_length=64)),
                ('status', models.BooleanField(null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
                ('datetime', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('txid', models.CharField(blank=True, max_length=66, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('original_file', models.FileField(upload_to='')),
                ('censored_file', models.FileField(blank=True, null=True, upload_to='')),
                ('processed', models.BooleanField(default=False)),
                ('copies', models.PositiveBigIntegerField(default=1)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
                ('censored_video', models.BooleanField(default=False)),
                ('original_video', models.BooleanField(default=False)),
                ('moderation_passed', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('minted', models.BooleanField(default=False)),
            ],
        ),
    ]
