# Generated by Django 3.2.4 on 2021-06-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=64)),
                ('username', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('name', models.TextField()),
                ('bio', models.TextField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='')),
                ('twitch', models.CharField(blank=True, max_length=64, null=True)),
                ('instagram', models.CharField(blank=True, max_length=64, null=True)),
                ('twitter', models.CharField(blank=True, max_length=64, null=True)),
                ('onlyfans', models.CharField(blank=True, max_length=64, null=True)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
