# Generated by Django 3.2.4 on 2021-07-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_squashed_0011_artwork_minted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawrequest',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
