# Generated by Django 3.2.4 on 2021-06-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='_wallet_pk',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='balance_bnb',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=64),
        ),
        migrations.AddField(
            model_name='profile',
            name='balance_lof',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=64),
        ),
    ]
