# Generated by Django 3.2.4 on 2021-06-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210621_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='_wallet_address',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='_wallet_pk',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
