# Generated by Django 3.2.4 on 2021-06-21 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210621_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=18, default=0, max_digits=64)),
                ('currency', models.CharField(choices=[('bnb', 'Bnb'), ('lof', 'Lof')], max_length=3)),
                ('address', models.CharField(max_length=64)),
                ('status', models.BooleanField(null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
            ],
        ),
    ]
