# Generated by Django 3.2.4 on 2021-06-21 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_withdrawrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawrequest',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
