# Generated by Django 3.2.4 on 2021-07-28 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_token_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_price', models.DecimalField(decimal_places=18, max_digits=64)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('finished', 'Finished')], default='pending', max_length=8)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='app.token')),
            ],
        ),
        migrations.CreateModel(
            name='AuctionBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=18, max_digits=64)),
                ('won', models.BooleanField(default=False)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='app.auction')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='app.profile')),
            ],
        ),
    ]
