# Generated by Django 3.2.4 on 2021-06-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_withdrawrequest_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawrequest',
            name='txid',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
    ]
