# Generated by Django 3.2.4 on 2021-07-28 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auction_auctionbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='app.profile'),
        ),
    ]
