# Generated by Django 3.2.4 on 2021-08-02 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auction_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='owner',
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='ClaimableToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.PositiveBigIntegerField()),
                ('claimed', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawable_tokens', to='app.profile')),
            ],
        ),
    ]
