# Generated by Django 3.2.4 on 2021-07-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_artwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='censored_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artwork',
            name='original_video',
            field=models.BooleanField(default=False),
        ),
    ]
