# Generated by Django 3.2.4 on 2021-08-04 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_artwork_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='moderation_passed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='claimabletoken',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimable_tokens', to='app.profile'),
        ),
    ]
