# Generated by Django 3.2.6 on 2021-08-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210804_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='auction',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('finished', 'Finished')], db_index=True, default='pending', max_length=8),
        ),
    ]
