# Generated by Django 3.2.6 on 2021-08-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210819_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
