# Generated by Django 3.2.6 on 2021-08-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_profile_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='top_slider',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
