# Generated by Django 3.2.6 on 2021-08-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_artwork_top_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='copy',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
