# Generated by Django 3.2.6 on 2021-08-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_token_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='block_creation',
            field=models.BooleanField(default=False),
        ),
    ]
