# Generated by Django 3.2.6 on 2021-10-24 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_profile_block_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='moderation_approved_by_default',
            field=models.BooleanField(default=False),
        ),
    ]
