# Generated by Django 3.2.6 on 2021-10-26 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_mintedtokensartwork'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MintedTokensArtwork',
        ),
    ]
